{% set name = "masci-tools" %}
{% set version = "0.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/masci_tools-{{ version }}.tar.gz
  sha256: 67099a7c15fd2884af49de110d1b6e6308e2703978d70dd8c597158b1622561a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ase
    - deepdiff
    - future
    - h5py
    - humanfriendly
    - lxml >=4.5
    - matplotlib-base
    - mendeleev
    - more-itertools
    - numpy
    - pandas
    - python >=3.7
    - scipy
    - seaborn
    - bump2version
    - click
    - click-completion
    - tabulate
    - pyyaml
    - typing-extensions

test:
  imports:
    - masci_tools
    - masci_tools.io
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/JuDFTteam/masci-tools
  summary: Python toolbox for juDFT codes
  description: |
    Collection of tools for Materials science.
    Focused on working with input/output from the Fleur and KKR codes developed at the FZ Juelich,
    but many routines can be used in a wider context.
    Also contains routines for visualization of standard material science results with matplotlib/bokeh
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janssenhenning
