{% set name = "masci-tools" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/masci_tools-{{ version }}.tar.gz
  sha256: 79c37c00350021efbd23e916235a08cfc5899d90dc500bdd3a8016c5e01e8d10

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - deepdiff
    - future
    - h5py
    - humanfriendly
    - lxml >=4.5
    - matplotlib-base
    - mendeleev <0.8.0
    - more-itertools
    - numpy
    - pandas
    - python >=3.6
    - scipy
    - seaborn
    - bump2version

test:
  imports:
    - masci_tools
    - masci_tools.io
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/JuDFTteam/masci-tools
  summary: Python toolbox for juDFT codes
  description: |
    Collection of tools for Materials science.
    Focused on working with input/output from the Fleur and KKR codes developed at the FZ Juelich,
    but many routines can be used in a wider context.
    Also contains routines for visualization of standard material science results with matplotlib/bokeh
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janssenhenning
